{% set name = "langgraph-prebuilt" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langgraph_prebuilt-{{ version }}.tar.gz
  sha256: c295f31328462034f457a1560c7d87e6433571be2a7aa3a16dd8e17199b79493

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langgraph-checkpoint >=2.1.0
    - langchain-core >=0.3.22
    - langgraph

test:
  imports:
    - langgraph.prebuilt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: Library with high-level APIs for creating and executing LangGraph agents and tools.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
